version: '2.1'
orbs:
  aws-cli: circleci/aws-cli@2.0
jobs:
  aws-cli-example:
    executor: aws-cli/default
    steps:
      - checkout
      - aws-cli/setup:
         aws-access-key-id: ACCESS_KEY_ID
         aws-secret-access-key: SECRET_ACCESS_KEY
         aws-region: AWS_REGION
      - run: echo "Run your code here"
      - run:
          name: open IP
          command: |
            public_ip_address=$(wget -qO- http://checkip.amazonaws.com)
            echo "this computers public ip address is $public_ip_address"
            aws ec2 authorize-security-group-ingress --region $AWS_REGION --group-id sg-0b32daaf6660f672e --ip-permissions "[{\"IpProtocol\": \"tcp\", \"FromPort\": 443, \"ToPort\": 443, \"IpRanges\": [{\"CidrIp\": \"${public_ip_address}/32\"}]}]"
      - run:
          name: Do stuff
          command: echo "foo" && exit 1 # cause an error, which will halt the job.
      - run:
          name: Clear Allow List
          command: aws ec2 revoke-security-group-ingress --region $AWS_REGION --group-id sg-0b32daaf6660f672e --protocol tcp --port 443 --cidr ${public_ip_address}/32
          when: always # Will run no matter if a previous step has failed
workflows:
   aws-cli:
     jobs:
     - aws-cli-example:
         context: test